baseURL = "http://blog.zhangyaqi.com/"
languageCode = "zh-cn"
title = "淼淼淼淼淼淼淼"
theme = "cleanwhite"

## 是否禁止URL Path转小写
disablePathToLower = true
## 保持分类的原始名字（false会做转小写处理）
preserveTaxonomyNames = true
disableLiveReload = true
# 全局开关，你也可以在每一篇内容的 front matter 中针对单篇内容关闭或开启某些功能
toc = true  # 是否开启目录

[author]
  name = "淼淼淼淼淼淼淼"

#  [[params.addtional_menus]]
#  title =  "关于"
#  href =  "/about/"
  [[params.addtional_menus]]
  title =  "ABOUT"
  href =  "/top/about/"

[params]
    author = "张亚奇"
    subtitle = "我从PHP来，当下专注于Go语言(golang)、物联网，目标在项目管理、系统架构"
    keywords = "golang,go语言,go语言笔记,go语言博客,公众号,小程序"
    description = "专注于IT物联网，包括但不限于Go语言(golang)、项目管理、系统管理、系统架构等"

## 配置代码高亮
[markup]
  [markup.tableOfContents]
    endLevel = 2
    startLevel = 1
  [markup.highlight]
    style = "dracula"